# Generated by Django 5.0 on 2024-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='rss_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
