# Generated by Django 5.0 on 2024-01-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niche', '0002_niche_rss_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niche',
            name='rss_url',
        ),
    ]
