# Generated by Django 5.0 on 2024-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche', '0003_remove_niche_rss_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='niche',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='niche',
            name='schedule',
            field=models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY')], default='DAILY', max_length=25),
        ),
    ]
