# Generated by Django 5.0 on 2024-01-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niche', '0005_niche_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niche',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda.'),
            preserve_default=False,
        ),
    ]
