# Generated by Django 5.0 on 2024-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='snoozed',
            field=models.BooleanField(default=False),
        ),
    ]
