# Generated by Django 5.0 on 2024-01-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_category_alter_newsletter_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
